// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/nicolad/go-movie-app/omdb"
)

type User struct {
	ID    string        `json:"id"`
	Name  string        `json:"name"`
	Likes []*omdb.Movie `json:"likes"`
}
