// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Movie struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Year  string `json:"year"`
}

type User struct {
	ID    string   `json:"id"`
	Name  string   `json:"name"`
	Likes []*Movie `json:"likes"`
}
